name: USC infinity app build

on: [ push ]

jobs:
  docker-build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: tonylixu/infinity

      - name: Build and tag image
        env:
          DOCKER_REGISTRY: tonylixu
          DOCKER_REPOSITORY: infinity
          IMAGE_TAG: latest
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG -f ./Dockerfile .

      - name: Push image to Docker Hub if main branch
        env:
          DOCKER_REGISTRY: tonylixu
          DOCKER_REPOSITORY: infinity
          IMAGE_TAG: latest
        run: |
          echo "${GITHUB_REF##*/}"
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
          fi

  notify-build:
    needs: docker-build
    runs-on: ubuntu-18.04
    steps:
      - name: action-slack
        uses: 8398a7/action-slack@v3.8.2
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,ref,job,took
          mention: 'here'
          if_mention: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always() # Pick up events even if the job fails or is canceled.
